In [1]:
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
supersectors=pd.read_csv('../data/SuperSectorJobLevels.csv')

In [31]:
supersectors.head()

,SuperSector,Feb2020_total,Feb2020_women,Feb2021_total,Feb2021_women,% Women Field,12MO Net Change All_Neg,12MO Net Change_Neg,% Women Job Loss,12Mo % Changeall,12Mo % Change,12Mo Net Change,12Mo Net Change All
0,Mining and logging,690.0,89.0,590.0,81.0,0.128986,-100.0,-8.0,0.080000,-0.144928,-0.089888,8000.0,100000.0
1,Construction,7648.0,996.0,7356.0,992.0,0.130230,-292.0,-4.0,0.013699,-0.038180,-0.004016,4000.0,292000.0
2,Manufacturing: Durable Goods,8007.0,1947.0,7590.0,1862.0,0.243162,-417.0,-85.0,0.203837,-0.052079,-0.043657,85000.0,417000.0
3,Manufacturing: Nondurable Goods,4792.0,1724.0,4641.0,1654.0,0.359766,-151.0,-70.0,0.463576,-0.031511,-0.040603,70000.0,151000.0
4,Wholesale trade,5895.2,1770.9,5637.6,1689.3,0.300397,-257.6,-81.6,0.316770,-0.043697,-0.046078,81600.0,257600.0

In [12]:
supersectors['% Women Field'] = supersectors['Feb2020_women']/supersectors['Feb2020_total']

In [16]:
supersectors['12MO Net Change All_Neg']=supersectors['Feb2021_total']-supersectors['Feb2020_total']

In [18]:
supersectors['12MO Net Change_Neg']=supersectors['Feb2021_women']-supersectors['Feb2020_women']

In [22]:
supersectors['% Women Job Loss'] = supersectors['12MO Net Change_Neg']/supersectors['12MO Net Change All_Neg']

In [24]:
supersectors['12Mo % Changeall']=supersectors['12MO Net Change All_Neg']/supersectors['Feb2020_total']

In [26]:
supersectors['12Mo % Change']=supersectors['12MO Net Change_Neg']/supersectors['Feb2020_women']

In [28]:
supersectors['12Mo Net Change']=-1000*supersectors['12MO Net Change_Neg']

In [30]:
supersectors['12Mo Net Change All']=-1000*supersectors['12MO Net Change All_Neg']

In [32]:
supersectors['% Men Field']=1-supersectors['% Women Field']

In [33]:
supersectors['% Men Job Loss']=1-supersectors['% Women Job Loss']

In [34]:
supersectors.head()

,SuperSector,Feb2020_total,Feb2020_women,Feb2021_total,Feb2021_women,% Women Field,12MO Net Change All_Neg,12MO Net Change_Neg,% Women Job Loss,12Mo % Changeall,12Mo % Change,12Mo Net Change,12Mo Net Change All,% Men Field,% Men Job Loss
0,Mining and logging,690.0,89.0,590.0,81.0,0.128986,-100.0,-8.0,0.080000,-0.144928,-0.089888,8000.0,100000.0,0.871014,0.920000
1,Construction,7648.0,996.0,7356.0,992.0,0.130230,-292.0,-4.0,0.013699,-0.038180,-0.004016,4000.0,292000.0,0.869770,0.986301
2,Manufacturing: Durable Goods,8007.0,1947.0,7590.0,1862.0,0.243162,-417.0,-85.0,0.203837,-0.052079,-0.043657,85000.0,417000.0,0.756838,0.796163
3,Manufacturing: Nondurable Goods,4792.0,1724.0,4641.0,1654.0,0.359766,-151.0,-70.0,0.463576,-0.031511,-0.040603,70000.0,151000.0,0.640234,0.536424
4,Wholesale trade,5895.2,1770.9,5637.6,1689.3,0.300397,-257.6,-81.6,0.316770,-0.043697,-0.046078,81600.0,257600.0,0.699603,0.683230

In [36]:
supersectors.to_csv ('../data/combined_supersector_frompython.csv', index = False, header=True)